trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'

parameters:
- name: runTests
  displayName: Run tests
  type: boolean
  default: true
- name: runOWASPScan
  displayName: Run OWASPScan
  type: boolean
  default: false
- name: sonarqubeInstance
  displayName: 'Select SonarQube for v9.9 or SonarQubeLatest for 10.4'
  type: string
  default: 'SonarQubeLatest'
  values:
  - 'SonarQube'
  - 'SonarQubeLatest'
  - name: 
    value: True
  - name: runAutomationTests #will let us toggle automation tests on or off
  displayName: run Automation Tests
  type: boolean
  value: True

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/DEV11-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: EPR.Payment.Facade
  - name: testProjectFolder
    value: EPR.Payment.Facade.Common.UnitTests
  - name: sonarQubeProjectKey
    value: epr-payment-facade
  - name: sonarQubeProjectName
    value: epr-payment-facade
  - name: runNugetTasks
    value: false
  - name: dotnetVersion
    value: dotnetVersion8
  - name: runAutomationTests #will let us toggle automation tests on or off
    value: True

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: upgrade-net-8

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ parameters.runTests }}
    runOWASPScan: ${{ parameters.runOWASPScan }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
    dotnetVersion: ${{ variables.dotnetVersion }}
    runAutomationTests: ${{ parameters.runAutomationTests }}
