variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprpaymentfacade'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprpaymentfacaderepository'
  serviceName: 'prdrwdwebwab424'
